<?php
// Sertakan file koneksi ke database (gantilah sesuai dengan pengaturan koneksi Anda)
require '../../config/Connections.php';
ob_start();  // Start output buffering
$id = $_POST['no_ppp'];
$tahun_ppp = $_POST['tahun_ppp'];
$nama_marketing = $_POST['nama_marketing'];
$kategoriListing = $_POST['kategoriListing'];
$jenisTransaksi = $_POST['jenisTransaksi'];
$jenisListing = $_POST['jenisListing'];
$besaranKomisi = $_POST['besaranKomisi'];
$jangkaWaktu = $_POST['jangkaWaktu'];
$sampaiDengan = $_POST['jangkaWaktu2'];
$jenisProperti = $_POST['jenisProperti'];
$luasTanah = $_POST['luasTanah'];
$luasBangunan = $_POST['luasBangunan'];
$area = $_POST['area'];
$blok = $_POST['blok'];
$hadapView = $_POST['hadapView'];
$jumlahLantai = $_POST['jumlahLantai'];
$alamatListingProperti = $_POST['alamatListingProperti'];
$hargaJual = $_POST['hargaJual'];
$minLamaSewa = $_POST['minLamaSewa'];
$deposit = $_POST['deposit'];
$hargaSewa = $_POST['hargaSewa'];
$cbSHM = $_POST['cbSHM'];
$noSHM = $_POST['noSHM'];
$cbHGB = $_POST['cbHGB'];
$noHGB = $_POST['noHGB'];
$tahunHGB = $_POST['tahunHGB'];
$cbIMB = $_POST['cbIMB'];
$noIMB = $_POST['noIMB'];
$cbPBB = $_POST['cbPBB'];
$noPBB = $_POST['noPBB'];
$tahunPBB = $_POST['tahunPBB'];
$cbNoHp = $_POST['cbNoHp'];
$noHP = $_POST['noHP'];
$cbDokLainnya = $_POST['cbDokLainnya'];
$dokLainnya = $_POST['dokLainnya'];
$cbKamarTidur = $_POST['cbKamarTidur'];
$kamarTidur = $_POST['kamarTidur'];
$cbKamarMandi = $_POST['cbKamarMandi'];
$kamarMandi = $_POST['kamarMandi'];
$cbCarport = $_POST['cbCarport'];
$carport = $_POST['carport'];
$cbRuangTamu = $_POST['cbRuangTamu'];
$cbRuangKeluarga = $_POST['cbRuangKeluarga'];
$cbRuangKerja = $_POST['cbRuangKerja'];
$cbKolamRenang = $_POST['cbKolamRenang'];
$cbTaman = $_POST['cbTaman'];
$cbTeras = $_POST['cbTeras'];
$cbGudang = $_POST['cbGudang'];
$cbDapur = $_POST['cbDapur'];
$kt_pembantu = $_POST['kt_pembantu'];
$km_pembantu = $_POST['km_pembantu'];
$cbListrik = $_POST['cbListrik'];
$wattListrik = $_POST['wattListrik'];
$cbTelepon = $_POST['cbTelepon'];
$lineTelepon = $_POST['lineTelepon'];
$lokasiTanah = $_POST['lokasiTanah'];
$cbAC = $_POST['cbAC'];
$unitAC = $_POST['unitAC'];
$cbFurnished = $_POST['cbFurnished'];
$cbUnfurnished = $_POST['cbUnfurnished'];
$cbSemiFurnished = $_POST['cbSemiFurnished'];
$cbAirPAM = $_POST['cbAirPAM'];
$cbAirTanah = $_POST['cbAirTanah'];
$cbWaterHeater = $_POST['cbWaterHeater'];
$fasKeterangan = $_POST['fasKeterangan'];
$namaPemilik = $_POST['namaPemilik'];
$noKTPPemilik = $_POST['noKTPPemilik'];
$noHPPemilik = $_POST['noHPPemilik'];
$noTelpRumahPemilik = $_POST['noTelpRumahPemilik'];
$emailPemilik = $_POST['emailPemilik'];
$alamatPemilik = $_POST['alamatPemilik'];
$namaAgent = $_POST['namaAgent'];
$kantorAgent = $_POST['kantorAgent'];
$noHPAgent = $_POST['noHPAgent'];
$telpKantor = $_POST['telpKantor'];
$emailAgent = $_POST['emailAgent'];
$alamatAgent = $_POST['alamatAgent'];

$tahun_ppp = mysqli_real_escape_string($conn, $tahun_ppp);
$nama_marketing = mysqli_real_escape_string($conn, $nama_marketing);
$kategoriListing  = mysqli_real_escape_string($conn, $kategoriListing );
$jenisTransaksi  = mysqli_real_escape_string($conn, $jenisTransaksi );
$jenisListing  = mysqli_real_escape_string($conn, $jenisListing );
$besaranKomisi  = mysqli_real_escape_string($conn, $besaranKomisi );
$jangkaWaktu  = mysqli_real_escape_string($conn, $jangkaWaktu );
$sampaiDengan  = mysqli_real_escape_string($conn, $sampaiDengan );
$lokasiTanah = mysqli_real_escape_string($conn, $lokasiTanah);
$jenisProperti  = mysqli_real_escape_string($conn, $jenisProperti );
$luasTanah  = mysqli_real_escape_string($conn, $luasTanah );
$luasBangunan  = mysqli_real_escape_string($conn, $luasBangunan );
$area  = mysqli_real_escape_string($conn, $area );
$blok  = mysqli_real_escape_string($conn, $blok );
$hadapView  = mysqli_real_escape_string($conn, $hadapView );
$jumlahLantai  = mysqli_real_escape_string($conn, $jumlahLantai );
$alamatListingProperti  = mysqli_real_escape_string($conn, $alamatListingProperti );
$hargaJual  = mysqli_real_escape_string($conn, $hargaJual );
$minLamaSewa  = mysqli_real_escape_string($conn, $minLamaSewa );
$deposit  = mysqli_real_escape_string($conn, $deposit );
$hargaSewa  = mysqli_real_escape_string($conn, $hargaSewa );
$cbSHM  = mysqli_real_escape_string($conn, $cbSHM );
$noSHM  = mysqli_real_escape_string($conn, $noSHM );
$cbHGB  = mysqli_real_escape_string($conn, $cbHGB );
$noHGB  = mysqli_real_escape_string($conn, $noHGB );
$tahunHGB  = mysqli_real_escape_string($conn, $tahunHGB );
$cbIMB  = mysqli_real_escape_string($conn, $cbIMB );
$noIMB  = mysqli_real_escape_string($conn, $noIMB );
$cbPBB  = mysqli_real_escape_string($conn, $cbPBB );
$noPBB  = mysqli_real_escape_string($conn, $noPBB );
$tahunPBB  = mysqli_real_escape_string($conn, $tahunPBB );
$cbNoHp  = mysqli_real_escape_string($conn, $cbNoHp );
$noHP  = mysqli_real_escape_string($conn, $noHP );
$cbDokLainnya  = mysqli_real_escape_string($conn, $cbDokLainnya );
$dokLainnya  = mysqli_real_escape_string($conn, $dokLainnya );
$cbKamarTidur  = mysqli_real_escape_string($conn, $cbKamarTidur );
$kamarTidur  = mysqli_real_escape_string($conn, $kamarTidur );
$cbKamarMandi  = mysqli_real_escape_string($conn, $cbKamarMandi );
$kamarMandi  = mysqli_real_escape_string($conn, $kamarMandi );
$cbCarport  = mysqli_real_escape_string($conn, $cbCarport );
$carport  = mysqli_real_escape_string($conn, $carport );
$cbRuangTamu  = mysqli_real_escape_string($conn, $cbRuangTamu );
$cbRuangKeluarga  = mysqli_real_escape_string($conn, $cbRuangKeluarga );
$cbRuangKerja  = mysqli_real_escape_string($conn, $cbRuangKerja );
$cbKolamRenang  = mysqli_real_escape_string($conn, $cbKolamRenang );
$cbTaman  = mysqli_real_escape_string($conn, $cbTaman );
$cbTeras  = mysqli_real_escape_string($conn, $cbTeras );
$cbGudang  = mysqli_real_escape_string($conn, $cbGudang );
$cbDapur  = mysqli_real_escape_string($conn, $cbDapur );
$kt_pembantu  = mysqli_real_escape_string($conn, $kt_pembantu );
$km_pembantu  = mysqli_real_escape_string($conn, $km_pembantu );
$cbListrik  = mysqli_real_escape_string($conn, $cbListrik );
$wattListrik  = mysqli_real_escape_string($conn, $wattListrik );
$cbTelepon  = mysqli_real_escape_string($conn, $cbTelepon );
$lineTelepon  = mysqli_real_escape_string($conn, $lineTelepon );
$cbAC  = mysqli_real_escape_string($conn, $cbAC );
$unitAC  = mysqli_real_escape_string($conn, $unitAC );
$cbFurnished  = mysqli_real_escape_string($conn, $cbFurnished );
$cbUnfurnished  = mysqli_real_escape_string($conn, $cbUnfurnished );
$cbSemiFurnished  = mysqli_real_escape_string($conn, $cbSemiFurnished );
$cbAirPAM  = mysqli_real_escape_string($conn, $cbAirPAM );
$cbAirTanah  = mysqli_real_escape_string($conn, $cbAirTanah );
$cbWaterHeater  = mysqli_real_escape_string($conn, $cbWaterHeater );
$fasKeterangan  = mysqli_real_escape_string($conn, $fasKeterangan );
$namaPemilik  = mysqli_real_escape_string($conn, $namaPemilik );
$noKTPPemilik  = mysqli_real_escape_string($conn, $noKTPPemilik );
$noHPPemilik  = mysqli_real_escape_string($conn, $noHPPemilik );
$noTelpRumahPemilik  = mysqli_real_escape_string($conn, $noTelpRumahPemilik );
$emailPemilik  = mysqli_real_escape_string($conn, $emailPemilik );
$alamatPemilik  = mysqli_real_escape_string($conn, $alamatPemilik );
$namaAgent  = mysqli_real_escape_string($conn, $namaAgent );
$kantorAgent  = mysqli_real_escape_string($conn, $kantorAgent );
$noHPAgent  = mysqli_real_escape_string($conn, $noHPAgent );
$telpKantor  = mysqli_real_escape_string($conn, $telpKantor );
$emailAgent  = mysqli_real_escape_string($conn, $emailAgent );
$alamatAgent  = mysqli_real_escape_string($conn, $alamatAgent );

$query = "UPDATE onlinelisting SET
  tahun_ppp = '$tahun_ppp',
  nama_marketing = '$nama_marketing',
  kategoriListing = '$kategoriListing',
  jenisTransaksi = '$jenisTransaksi',
  jenisListing = '$jenisListing',
  besaranKomisi = '$besaranKomisi',
  jangkaWaktu = '$jangkaWaktu',
  sampaiDengan = '$sampaiDengan',
  lokasiTanah = '$lokasiTanah',
  jenisProperti = '$jenisProperti',
  luasTanah = '$luasTanah',
  luasBangunan = '$luasBangunan',
  area = '$area',
  blok = '$blok',
  hadapView = '$hadapView',
  jumlahLantai = '$jumlahLantai',
  alamatListingProperti = '$alamatListingProperti',
  hargaJual = '$hargaJual',
  minLamaSewa = '$minLamaSewa',
  deposit = '$deposit',
  hargaSewa = '$hargaSewa',
  cbSHM = '$cbSHM',
  noSHM = '$noSHM',
  cbHGB = '$cbHGB',
  noHGB = '$noHGB',
  tahunHGB = '$tahunHGB',
  cbIMB = '$cbIMB',
  noIMB = '$noIMB',
  cbPBB = '$cbPBB',
  noPBB = '$noPBB',
  tahunPBB = '$tahunPBB',
  cbNoHp = '$cbNoHp',
  noHP = '$noHP',
  cbDokLainnya = '$cbDokLainnya',
  dokLainnya = '$dokLainnya',
  cbKamarTidur = '$cbKamarTidur',
  kamarTidur = '$kamarTidur',
  cbKamarMandi = '$cbKamarMandi',
  kamarMandi = '$kamarMandi',
  cbCarport = '$cbCarport',
  carport = '$carport',
  cbRuangTamu = '$cbRuangTamu',
  cbRuangKeluarga = '$cbRuangKeluarga',
  cbRuangKerja = '$cbRuangKerja',
  cbKolamRenang = '$cbKolamRenang',
  cbTaman = '$cbTaman',
  cbTeras = '$cbTeras',
  cbGudang = '$cbGudang',
  cbDapur = '$cbDapur',
  kt_pembantu = '$kt_pembantu',
  km_pembantu = '$km_pembantu',
  cbListrik = '$cbListrik',
  wattListrik = '$wattListrik',
  cbTelepon = '$cbTelepon',
  lineTelepon = '$lineTelepon',
  cbAC = '$cbAC',
  unitAC = '$unitAC',
  cbFurnished = '$cbFurnished',
  cbUnfurnished = '$cbUnfurnished',
  cbSemiFurnished = '$cbSemiFurnished',
  cbAirPAM = '$cbAirPAM',
  cbAirTanah = '$cbAirTanah',
  cbWaterHeater = '$cbWaterHeater',
  fasKeterangan = '$fasKeterangan',
  namaPemilik = '$namaPemilik',
  noKTPPemilik = '$noKTPPemilik',
  noHPPemilik = '$noHPPemilik',
  noTelpRumahPemilik = '$noTelpRumahPemilik',
  emailPemilik = '$emailPemilik',
  alamatPemilik = '$alamatPemilik',
  namaAgent = '$namaAgent',
  kantorAgent = '$kantorAgent',
  noHPAgent = '$noHPAgent',
  telpKantor = '$telpKantor',
  emailAgent = '$emailAgent',
  alamatAgent = '$alamatAgent'
WHERE no_ppp = '$id'";
$hasil = mysqli_query($conn, $query);
ob_end_clean();  // Discard the output buffer
if ($hasil) {
    echo "Formulir berhasil diupdate<br>";
    header("Location: ../viewDataListing.php");
} else {
    echo "Formulir gagal diupdate";
}
